/* Configuration for libhello generated by Alire */
#ifndef LIBHELLO_CONFIG_H
#define LIBHELLO_CONFIG_H

#define CRATE_VERSION "1.0.1"
#define CRATE_NAME "libhello"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
